# https://github.com/qmk/qmk_firmware/blob/master/docs/newbs_building_firmware_workflow.md
name: QMK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
      - name: Disable git safe directory checks
        run: git config --global --add safe.directory '*'
      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          submodules: recursive
      - name: Checkout personal keymaps
        uses: actions/checkout@v3
        with:
          sparse-checkout: dztech_dz60rgb_wkl/keymaps/haunt98
          path: ~/qmk_firmware/keyboards/dztech/dz60rgb_wkl/keymaps
      - name: Build firmware
        run: qmk compile -j 8 -kb dztech/dz60rgb_wkl/v2_1 -km haunt98
      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: dztech_dz60rgb_wkl_haunt98
          path: |
            *.hex
            *.bin
            *.uf2
